
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g mouse on

set -g base-index 1
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g default-terminal "${TERM}"
setw -g mode-keys vi


%if #{os} = "Windows_NT"

  set -g @plugin 'psmux-plugins/ppm'
  set -g @plugin 'psmux-plugins/psmux-sensible'
  set -g @plugin 'psmux-plugins/psmux-pain-control'
  set -g @plugin 'psmux-plugins/psmux-prefix-highlight'

  # set -g @plugin 'psmux-plugins/psmux-theme-nord'
  set -g @plugin 'psmux-plugins/psmux-theme-catppuccin'
  set -g @catppuccin-flavor 'frappe'
  set -g @catppuccin-separator-style 'slanted'
  set -g @catppuccin-show-powerline 'on'
  set -g @catppuccin-show-host 'on'

  set -g status-position top       # macOS / darwin style

  # must call .ps1 for options to have an effect
  run-shell 'pwsh -NoProfile -File "$env:USERPROFILE/.psmux/plugins/psmux-theme-catppuccin/psmux-theme-catppuccin.ps1"'

  # Initialize PPM (keep this line at the very bottom of .psmux.conf)
  run '~/.psmux/plugins/ppm/ppm.ps1'

%else
# macOS/linux:
  set -g @plugin 'tmux-plugins/tpm'
  set -g @plugin 'tmux-plugins/tmux-sensible'
  set -g @plugin 'catppuccin/tmux'

  set -g @catppuccin-window-style 'rounded'
  set -g @catppuccin_window_left_separator ""
  set -g @catppuccin_window_right_separator " "
  set -g @catppuccin_window_middle_separator " █"
  set -g @catppuccin_window_number_position "right"
  set -g @catppuccin_window_default_fill "number"
  set -g @catppuccin_window_default_text "#W"
  set -g @catppuccin_window_current_fill "number"
  set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
  set -g @catppuccin_status_modules_right "directory" # date_time"
  set -g @catppuccin_status_modules_left "session"
  set -g @catppuccin_status_left_separator  " "
  set -g @catppuccin_status_right_separator " "
  set -g @catppuccin_status_right_separator_inverse "no"
  set -g @catppuccin_status_fill "icon"
  set -g @catppuccin_status_connect_separator "no"
  set -g @catppuccin_directory_text "#{b:pane_current_path}"
%endif

