# ~/.config/zsh/.zshenv
#
# to bootstrap zsh to this config, ensure /etc/zshenv has this entry:
#
# if [[ -d "$HOME/.config/zsh" ]]
# then
# 	export ZDOTDIR="$HOME/.config/zsh"
# fi

# ---------- XDG base directories ----------
# Centralizes config/cache/data locations
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export EDITOR="nvim"
export VISUAL="nvim"
export LESS="-c -i -x4 -J -w -M -r"

if [[ ! -d "$XDG_DATA_HOME/zsh" ]]
then
    mkdir -p "$XDG_DATA_HOME/zsh"
fi
if [[ ! -d "$XDG_STATE_HOME/zsh" ]]
then
    mkdir -p "$XDG_STATE_HOME/zsh"
fi

if command -v bat >/dev/null 2>&1; then
  export MANPAGER="bat -l man -p"
fi

export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship.toml"

export PATH="$HOME/.local/bin:$PATH"
